services:
  backend:
    build:
      context: ./node-backend
      dockerfile: Dockerfile
    container_name: node-backend
    ports:
      - "8000:3001"  # Mapeamos el puerto 8000 del host al 3001 del contenedor
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./node-backend/data:/app/data  # Mapear el directorio de datos de SQLite

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  frontend_data:
